### ISSUE TITLE
Epic: MPAS System

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/MPAS#7]
**Description**: The MPAS System enables automatic subscription, distribution and deployment of products (based on the Open Component Model) using GitOps paradigms, integrated localization and configuration product template mechanisms, as well as version-controlled and validation-enabled Git-based product configuration management.

The work required for the MVP of the MPAS System is divided into several individual work packages, described as User Stories:

- [x] MPAS setup & configuration: https://github.com/open-component-model/MPAS/issues/3
- [x] The MPAS "Project"-Entity: https://github.com/open-component-model/MPAS/issues/4
- [x] Deployment Targets: https://github.com/open-component-model/MPAS/issues/2
- [x] Product Subscriptions: https://github.com/open-component-model/MPAS/issues/1
- [x] Product Installations: https://github.com/open-component-model/MPAS/issues/6
- [x] Packaging MPAS-compliant Products: https://github.com/open-component-model/MPAS/issues/5

Apart from these individual User Stories, it is required to define an example, which runs through the complete MPAS System, using the end2end-test-framework.
